import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import themes from '@/themes';
import '../assets/scss/style.scss';
import AuthProvider from '@/state/auth/Provider'
import Head from "next/head";

export const metadata: Metadata = {
  title: "T1Games Lottery",
  description: "Generated by T1Games app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
       <Head>
       <link href="https://fonts.cdnfonts.com/css/futura-lt" rel="stylesheet" />
      </Head>
      <body >
        <AppRouterCacheProvider>
          <ThemeProvider theme={themes}>
            <AuthProvider>
            {children}
            </AuthProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
